# Common layout - applies to all profiles
layout:
  primary:
    top_left: com.google.Chrome
    top_right: com.microsoft.teams2
    bottom_left: com.microsoft.Outlook
    bottom_right: com.kakao.KakaoTalkMac
  builtin:
  - md.obsidian

# Monitor configurations for different setups
profiles:
  home:
    monitors:
    - resolution: 3840x2160
      position: primary
    - resolution: 2560x1440
      position: left
    - resolution: 2056x1329
      position: builtin
  office:
    monitors:
    - resolution: 3440x1440
      position: primary
    - resolution: 2560x1440
      position: left
    - resolution: macbook
      position: builtin
